version: '2'
services:
  app2:
    image: fdrennan/plumber
    command: /app/plumber.R
    volumes:
     - .:/app
    restart: always
    ports:
     - "8000:8000"
  app3:
    image: fdrennan/plumber
    command: /app/plumber.R
    volumes:
     - .:/app
    restart: always
    ports:
     - "8001:8000"
