version: '2'
services:
  app1:
    image: dockerfile
    command: /app/plumber.R
    volumes:
     - .:/app
    restart: always
  rstudio:
    image: rocker/rstudio
    volumes:
     - .:/app
    restart: always
    ports:
     - "8787:8787"
  nginx:
      image: nginx:1.9
      ports:
       - "80:80"
      volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
      restart: always
      depends_on:
       - app1
  lb:
      image: 'dockercloud/haproxy:1.2.1'
      links:
       - app1
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock